---
description:
  default_value:
  required: false
  value_type: string
display_name:
  default_value:
  required: true
  value_type: string
github_teams:
  default_value: []
  required: true
  value_type: array
google_groups:
  default_value: []
  required: true
  value_type: array
jira_project_name:
  default_value:
  required: false
  value_type: string
members:
  default_value: []
  required: true
  value_type: array
people_project_name:
  default_value:
  required: true
  value_type: string
pivotal_project_name:
  default_value:
  required: false
  value_type: string
project_email:
  default_value:
  required: true
  value_type: string
rollbar_teams:
  default_value: []
  required: true
  value_type: array
slack_client_channel_name:
  default_value:
  required: false
  value_type: string
slack_project_channel_name:
  default_value:
  required: true
  value_type: string
toggl_teams:
  default_value: []
  required: true
  value_type: array
