---
display_name:
  required: true
  default_value:
  value_type: string
description:
  required: false
  default_value:
  value_type: string
project_email:
  required: true
  default_value:
  value_type: string
slack_project_channel_name:
  required: true
  default_value:
  value_type: string
slack_client_channel_name:
  required: false
  default_value:
  value_type: string
github_teams:
  required: false
  default_value:
  value_type: array
google_groups:
  required: false
  default_value:
  value_type: array
people_project_name:
  required: true
  default_value:
  value_type: string
pivotal_project_name:
  required: false
  default_value:
  value_type: string
jira_project_name:
  required: false
  default_value:
  value_type: string
members:
  required: false
  default_value: []
  value_type: array
