---
members:
  required: true
  default_value: []
  value_type: array
name:
  required: true
  default_value: "Rollbar Team Name" # Can't be nil
  value_type: string
projects:
  required: true
  default_value: []
  value_type: array
