---
members:
  default_value: []
  required: true
  value_type: array
name:
  default_value: "Toggl Team Name" # Can't be nil
  required: true
  value_type: string
project:
  default_value:
  required: true
  value_type: string
tasks:
  default_value: []
  required: true
  value_type: array
